### ISSUE TITLE
[bug] You can add the same bot to the pack multiple times

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#223]
### Page

https://beta.discordlist.gg/bot/515067662028636170?message=success

### Description

Adding the bot to any pack, will let you to continuous get this message

<img width="313" alt="image" src="https://user-images.githubusercontent.com/58714825/169916696-52a1e223-8b66-4ecc-8842-f36fbf33798b.png">
 
 There is no notification of the bot already in the pack
 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/58714825/169916741-72e56737-76b7-4ca8-8981-0079b4881e51.png">

### Notify on issue updates

- [X] Yes

### Discord username

GamerCreator1#1466

**Comment by ChillFish8** [comment]
We established that this isn't really an issue, or an issue in the sense that we cant do anything about it. this de-duplication is done on the DB side within its types. So the backend really isn't any wiser to if the pack already exists or not. And in order to do that, would involve fetching the packs yet again.
