### ISSUE TITLE
[ui] Menu Improvements

### ISSUE THREAD

**Issue by Legit4K** [discordlist-gg/beta-issues#254]
### Description

![Screenshot_20220529_130433](https://user-images.githubusercontent.com/44619264/170867308-d3c3e494-4dce-442f-8a4b-5a325f774f88.jpg)

### Feedback Buttons
The **Feedback button** is redundant as it simply displays the word "feedback" when pressing it. I think it'd be best for it to be removed in favor of the already existing **New issue button.**

### Settings Buttons
Similarly, the **Settings button** and **Website Settings button** should also be combined to remove redundancy. Ofcourse, the text under it will need to be changed too if this makes its way into the beta.

### Submit New Bot Button
Together, those two suggestions will help clear up space in the menu for the return of the **Submit New Bot button** that was previously available before the menu rework. Not having that would be a fairly substantial missed opportunity as it locks mobile users from accessing core functionality of the platform.

### Help Button
Finally, the **Help button** is missing its text underneath. That should be added for consistency ofcourse :)

### Notify on issue updates

- [ ] Yes

**Comment by audn** [comment]
Hi,

> ### Feedback Buttons
The feedback modal for phone has not been created yet. That's why it's not showing anything useful.

Our goal with **Feedback** is to gather valuable feedback to improve our service, where as **New issue** is for reporting bugs / issues. 

The two "menu items" cannot be merged as they are different.

> ### Settings Buttons
We will not be merging **Website Settings** with **User Settings** as they both have "view rules" that don't comply with each other.
- User Settings: You're logged in and can manage your profile, payment details and delete your profile. (This is a much bigger thing than just "Settings". 
- Website Settings: You're not depended on being signed in.


> ### Submit New Bot Button
The button has always been there, but not in the menu you're currently in.

> Submit New Bot button that was previously available before the menu rework.
<img width="316" alt="image" src="https://user-images.githubusercontent.com/21041399/170981684-913ea906-3c39-4e0f-ad93-d46d78ae3476.png">


> ### Help Button
I'm going to have to decline this change simply because of your reasoning. 

The sole purpose of having a description is to help the user get to their destination, and the title itself for "Help" is already well explained considering it's a global word.


I will proceed to close the issue, but feel free to keep commenting if you have additional replies.

_Thank you for contributing during beta!_
