### ISSUE TITLE
[Suggestion] Create bot pack's while the "Let anyone add" option "OFF"

### ISSUE THREAD

**Issue by K-S-K-1** [discordlist-gg/beta-issues#293]
### Description
Allow bot owners to create bot pack's with there own bot's, while the "Let anyone add" option "OFF" 

![image](https://user-images.githubusercontent.com/105230844/172665077-5b0a26dc-3b3a-4b08-bd98-9ec88df4779c.png)

- [X] Yes

~ K S K ~™

**Comment by audn** [comment]
Hi,
We have come to the conclusion that this is a change request that we either don't want to prioritize during the beta phase, or because we simply do not see the need for it.

If desired, you are more than welcome to reopen the case *(preferably with a counter-argument)* - if you don't agree with our response.

I will proceed to close the issue.

_Thank you for contributing during beta!_
